from __future__ import annotations

SOURCES = {
    "ftc_social_scams_2026": {
        "label": "FTC social media scam spotlight",
        "date": "2026-04-27",
        "url": "https://www.ftc.gov/news-events/data-visualizations/data-spotlight/2026/04/reported-losses-scams-social-media-eight-times-higher-2020",
    },
    "ftc_fraud_2025_release": {
        "label": "FTC 2024 fraud loss release",
        "date": "2025-03-10",
        "url": "https://www.ftc.gov/news-events/news/press-releases/2025/03/new-ftc-data-show-big-jump-reported-losses-fraud-125-billion-2024",
    },
    "fbi_ic3_2026": {
        "label": "FBI / IC3 2025 report release",
        "date": "2026-04-06",
        "url": "https://www.fbi.gov/news/press-releases/cryptocurrency-and-ai-scams-bilk-americans-of-billions",
    },
    "gartner_service_2026": {
        "label": "Gartner service and support leaders survey",
        "date": "2026-02-18",
        "url": "https://www.gartner.com/en/newsroom/press-releases/2026-02-18-gartner-survey-finds-ninety-one-percent-of-customer-service-leaders-under-pressure-to-implement-ai-in-2026",
    },
    "medallia_cx_2026": {
        "label": "Medallia State of Customer Experience",
        "date": "2026-03-05",
        "url": "https://www.medallia.com/press-release/medallia-releases-2026-state-of-customer-experience-report/",
    },
    "qualtrics_cx_2026": {
        "label": "Qualtrics consumer experience trends",
        "date": "2026-01-01",
        "url": "https://www.qualtrics.com/en-gb/ebooks-guides/customer-experience-trends/",
    },
    "mcafee_scamiverse_2026": {
        "label": "McAfee State of the Scamiverse",
        "date": "2026-02-05",
        "url": "https://www.mcafee.com/en-in/consumer-corporate/newsroom/press-releases/2026/20260204-1.html",
    },
    "transunion_fraud_2026": {
        "label": "TransUnion top fraud trends update",
        "date": "2026-04-08",
        "url": "https://newsroom.transunion.com/h1-2026-update-to-the-top-fraud-trends-report/",
    },
    "microsoft_device_code_2026": {
        "label": "Microsoft AI-enabled device code phishing campaign",
        "date": "2026-04-06",
        "url": "https://www.microsoft.com/en-us/security/blog/2026/04/06/ai-enabled-device-code-phishing-campaign-april-2026/",
    },
}

VERTICALS = [
    ("ecommerce", "E-commerce", "shopping"),
    ("marketplace", "Online Marketplace", "shopping"),
    ("social_commerce", "Social Commerce", "shopping"),
    ("banking", "Banking", "finance"),
    ("fintech", "Fintech", "finance"),
    ("insurance", "Insurance", "finance"),
    ("crypto", "Crypto Exchange", "finance"),
    ("payments", "Payments", "finance"),
    ("healthcare", "Healthcare", "health"),
    ("telehealth", "Telehealth", "health"),
    ("pharmacy", "Pharmacy", "health"),
    ("education", "Education", "education"),
    ("edtech", "EdTech", "education"),
    ("job_board", "Job Board", "work"),
    ("hr_payroll", "HR and Payroll", "work"),
    ("gig_platform", "Gig Platform", "work"),
    ("travel", "Travel Booking", "travel"),
    ("hospitality", "Hospitality", "travel"),
    ("airline", "Airline", "travel"),
    ("real_estate", "Real Estate", "housing"),
    ("rentals", "Rental Listings", "housing"),
    ("home_services", "Home Services", "housing"),
    ("government", "Government Services", "public"),
    ("utilities", "Utilities", "public"),
    ("telecom", "Telecom", "infrastructure"),
    ("saas", "SaaS", "software"),
    ("developer_tools", "Developer Tools", "software"),
    ("streaming", "Streaming", "media"),
    ("subscription_media", "Subscription Media", "media"),
    ("gaming", "Gaming", "community"),
    ("dating", "Dating", "community"),
    ("community_forum", "Community Forum", "community"),
    ("creator_tools", "Creator Tools", "community"),
    ("ticketing", "Event Ticketing", "events"),
    ("food_delivery", "Food Delivery", "delivery"),
    ("logistics", "Logistics", "delivery"),
    ("mobility", "Mobility", "transport"),
    ("legal_services", "Legal Services", "professional"),
    ("fitness", "Fitness and Wellness", "lifestyle"),
    ("beauty", "Beauty Commerce", "lifestyle"),
    ("consumer_electronics", "Consumer Electronics", "retail"),
    ("auto_retail", "Auto Retail", "retail"),
    ("local_retail", "Local Retail", "retail"),
    ("nonprofit", "Nonprofit Giving", "civic"),
    ("pet_services", "Pet Services", "lifestyle"),
    ("childcare", "Childcare Services", "lifestyle"),
    ("procurement", "B2B Procurement", "enterprise"),
    ("cybersecurity", "Cybersecurity Vendor", "enterprise"),
]

ARCHETYPES = [
    {
        "slug": "imposter_scam",
        "macro_theme": "fraud",
        "title": "Users cannot tell real {vertical_label} outreach from imposter scams",
        "phrase": "I got a message that looked real, but I cannot tell if it is actually from {vertical_label}.",
        "why_now": "Imposter scams remain among the highest-loss internet complaints and AI-generated lures keep getting more convincing.",
        "severity": 94,
        "urgency": 92,
        "frequency": 88,
        "opportunity": 83,
        "ai_fit": 64,
        "sources": ["ftc_fraud_2025_release", "fbi_ic3_2026", "mcafee_scamiverse_2026"],
        "solution": "Trust verification layer, message provenance, and outbound notice registry.",
    },
    {
        "slug": "social_media_scam",
        "macro_theme": "fraud",
        "title": "Users get pulled from social feeds into fake {vertical_label} offers",
        "phrase": "The ad looked real on social media, but it turned into a scam when I tried to buy or sign up.",
        "why_now": "Social-originated scam losses keep rising and reach younger as well as older consumers.",
        "severity": 91,
        "urgency": 90,
        "frequency": 93,
        "opportunity": 82,
        "ai_fit": 59,
        "sources": ["ftc_social_scams_2026", "mcafee_scamiverse_2026", "transunion_fraud_2026"],
        "solution": "Link reputation, seller verification, and ad-to-checkout risk scoring.",
    },
    {
        "slug": "deepfake_voice_fraud",
        "macro_theme": "fraud",
        "title": "Users are vulnerable to deepfake or voice-clone fraud in {vertical_label}",
        "phrase": "The voice or video sounded real, and I only realized later it was fake.",
        "why_now": "Consumers increasingly encounter deepfake and voice-clone scams across daily digital interactions.",
        "severity": 95,
        "urgency": 94,
        "frequency": 74,
        "opportunity": 86,
        "ai_fit": 52,
        "sources": ["mcafee_scamiverse_2026", "fbi_ic3_2026"],
        "solution": "Out-of-band verification, secure callback flows, and synthetic-media detection.",
    },
    {
        "slug": "phishing_login_flow",
        "macro_theme": "identity",
        "title": "Users are tricked into phishing flows that mimic official {vertical_label} login pages",
        "phrase": "The login page looked official, so I entered the code or password without realizing it was a trap.",
        "why_now": "AI-enabled phishing kits are more automated, personalized, and harder to spot than older campaigns.",
        "severity": 96,
        "urgency": 95,
        "frequency": 81,
        "opportunity": 84,
        "ai_fit": 57,
        "sources": ["microsoft_device_code_2026", "mcafee_scamiverse_2026", "fbi_ic3_2026"],
        "solution": "Phishing-resistant authentication, origin validation, and login anomaly detection.",
    },
    {
        "slug": "job_opportunity_trap",
        "macro_theme": "fraud",
        "title": "Users chasing {vertical_label} opportunities fall into fake jobs or business offers",
        "phrase": "The opportunity sounded legitimate until they asked for money, documents, or off-platform contact.",
        "why_now": "Job and business opportunity scams have risen sharply and increasingly start on social media.",
        "severity": 88,
        "urgency": 87,
        "frequency": 79,
        "opportunity": 81,
        "ai_fit": 61,
        "sources": ["ftc_social_scams_2026", "ftc_fraud_2025_release"],
        "solution": "Listing verification, recruiter proofing, and payout-safe workflows.",
    },
    {
        "slug": "rental_listing_fraud",
        "macro_theme": "fraud",
        "title": "Users searching {vertical_label} listings cannot tell fake inventory from real supply",
        "phrase": "I spent time on a listing that turned out not to be real.",
        "why_now": "Rental and housing scams increasingly originate on social platforms and exploit urgency.",
        "severity": 87,
        "urgency": 85,
        "frequency": 73,
        "opportunity": 78,
        "ai_fit": 56,
        "sources": ["ftc_social_scams_2026", "ftc_fraud_2025_release"],
        "solution": "Listing authenticity scoring, owner proof, and anti-escrow fraud protections.",
    },
    {
        "slug": "investment_scam",
        "macro_theme": "fraud",
        "title": "Users are lured into fake {vertical_label} investment or yield schemes",
        "phrase": "The dashboard showed profits, but the whole thing was fake.",
        "why_now": "Investment scams remain one of the costliest categories and are often amplified by AI-generated trust cues.",
        "severity": 98,
        "urgency": 95,
        "frequency": 68,
        "opportunity": 80,
        "ai_fit": 49,
        "sources": ["fbi_ic3_2026", "ftc_fraud_2025_release", "ftc_social_scams_2026"],
        "solution": "Investment verification rails, high-risk claim detection, and suspicious transfer intervention.",
    },
    {
        "slug": "seller_trust_gap",
        "macro_theme": "marketplace",
        "title": "Users do not trust whether a {vertical_label} seller or provider is real",
        "phrase": "The listing looked normal, but I had no confidence the seller would actually deliver.",
        "why_now": "Third-party seller scams remain a consistent digital-fraud loss driver, especially in platform models.",
        "severity": 84,
        "urgency": 82,
        "frequency": 86,
        "opportunity": 85,
        "ai_fit": 66,
        "sources": ["transunion_fraud_2026", "ftc_social_scams_2026"],
        "solution": "Seller trust graphs, transaction guarantees, and identity-backed reputation.",
    },
    {
        "slug": "fake_reviews",
        "macro_theme": "trust",
        "title": "Users cannot trust reviews, ratings, or testimonials in {vertical_label}",
        "phrase": "Everything had good reviews, but I still got burned.",
        "why_now": "Trust signals are being gamed harder as acquisition gets more competitive and AI makes manipulation cheaper.",
        "severity": 78,
        "urgency": 73,
        "frequency": 89,
        "opportunity": 82,
        "ai_fit": 71,
        "sources": ["ftc_social_scams_2026", "medallia_cx_2026"],
        "solution": "Review authenticity, verified outcomes, and anomaly-based reputation scoring.",
    },
    {
        "slug": "delivery_confusion",
        "macro_theme": "operations",
        "title": "Users struggle to understand real delivery status in {vertical_label}",
        "phrase": "The tracking updates were confusing, delayed, or wrong.",
        "why_now": "Delivery notices are both a real service pain point and a scam lure, creating a trust and operations problem at once.",
        "severity": 76,
        "urgency": 71,
        "frequency": 88,
        "opportunity": 79,
        "ai_fit": 75,
        "sources": ["mcafee_scamiverse_2026", "medallia_cx_2026"],
        "solution": "Verified status feeds, exception alerts, and unified tracking UX.",
    },
    {
        "slug": "refund_delay",
        "macro_theme": "payments",
        "title": "Users cannot predict when {vertical_label} refunds will actually arrive",
        "phrase": "I was told the refund was processed, but I still had no idea when the money would show up.",
        "why_now": "Refund ambiguity compounds support load, negative sentiment, and scam susceptibility.",
        "severity": 80,
        "urgency": 78,
        "frequency": 84,
        "opportunity": 83,
        "ai_fit": 77,
        "sources": ["medallia_cx_2026", "qualtrics_cx_2026"],
        "solution": "Refund timelines, bank-status translation, and self-serve refund intelligence.",
    },
    {
        "slug": "billing_confusion",
        "macro_theme": "payments",
        "title": "Users do not understand {vertical_label} charges, renewals, or fee structure",
        "phrase": "I saw a charge I did not recognize or could not explain.",
        "why_now": "Consumers are more sensitive to billing surprises while scams and real charges increasingly blur together.",
        "severity": 82,
        "urgency": 79,
        "frequency": 87,
        "opportunity": 84,
        "ai_fit": 79,
        "sources": ["transunion_fraud_2026", "qualtrics_cx_2026", "medallia_cx_2026"],
        "solution": "Explainable billing, charge provenance, and proactive anomaly notices.",
    },
    {
        "slug": "subscription_cancellation",
        "macro_theme": "payments",
        "title": "Users cannot cancel or downgrade {vertical_label} subscriptions cleanly",
        "phrase": "I wanted to stop paying, but the cancellation flow felt hidden or misleading.",
        "why_now": "Subscription fatigue and regulatory scrutiny make cancellation friction especially damaging in 2026.",
        "severity": 75,
        "urgency": 72,
        "frequency": 82,
        "opportunity": 74,
        "ai_fit": 72,
        "sources": ["medallia_cx_2026", "qualtrics_cx_2026"],
        "solution": "Transparent offboarding, downgrade alternatives, and friction analytics.",
    },
    {
        "slug": "account_takeover",
        "macro_theme": "identity",
        "title": "Users lose access to {vertical_label} accounts through takeover or session theft",
        "phrase": "My account got hijacked or I was locked out after suspicious activity.",
        "why_now": "Account takeover remains a major loss vector, and session-token abuse is becoming more industrialized.",
        "severity": 94,
        "urgency": 91,
        "frequency": 76,
        "opportunity": 86,
        "ai_fit": 69,
        "sources": ["transunion_fraud_2026", "microsoft_device_code_2026", "mcafee_scamiverse_2026"],
        "solution": "Session risk scoring, recovery hardening, and impossible-travel style anomaly controls.",
    },
    {
        "slug": "password_reset_pain",
        "macro_theme": "identity",
        "title": "Users hit dead ends in {vertical_label} password reset and recovery flows",
        "phrase": "I followed the recovery flow but still could not get back in.",
        "why_now": "Identity friction is rising as sites add defenses, but recovery experiences often remain brittle and confusing.",
        "severity": 73,
        "urgency": 71,
        "frequency": 85,
        "opportunity": 81,
        "ai_fit": 74,
        "sources": ["transunion_fraud_2026", "gartner_service_2026"],
        "solution": "Adaptive recovery routing, identity proofing, and state-aware help flows.",
    },
    {
        "slug": "otp_mfa_fatigue",
        "macro_theme": "identity",
        "title": "Users in {vertical_label} face OTP and MFA fatigue without feeling truly protected",
        "phrase": "I keep getting codes and prompts, but I still do not feel safer.",
        "why_now": "MFA fatigue, push abuse, and device-code attacks show that more prompts are not the same as stronger trust.",
        "severity": 79,
        "urgency": 77,
        "frequency": 74,
        "opportunity": 78,
        "ai_fit": 67,
        "sources": ["microsoft_device_code_2026", "mcafee_scamiverse_2026"],
        "solution": "Phishing-resistant auth, prompt abuse detection, and human-readable risk cues.",
    },
    {
        "slug": "support_wait_time",
        "macro_theme": "support",
        "title": "Users cannot reach useful human support quickly in {vertical_label}",
        "phrase": "I kept going in circles before I could talk to someone who could actually help.",
        "why_now": "Organizations are pushing AI and self-service, but complex issues still depend on skilled human intervention.",
        "severity": 81,
        "urgency": 76,
        "frequency": 90,
        "opportunity": 85,
        "ai_fit": 80,
        "sources": ["gartner_service_2026", "medallia_cx_2026", "qualtrics_cx_2026"],
        "solution": "Intent-aware routing, better escalation triggers, and queue transparency.",
    },
    {
        "slug": "self_service_failure",
        "macro_theme": "support",
        "title": "Users try self-service in {vertical_label} but still end up stuck",
        "phrase": "The help center existed, but it did not solve my actual problem.",
        "why_now": "Self-service is a top 2026 priority, yet many organizations still fail at actionability and resolution quality.",
        "severity": 77,
        "urgency": 74,
        "frequency": 91,
        "opportunity": 84,
        "ai_fit": 86,
        "sources": ["gartner_service_2026", "qualtrics_cx_2026", "medallia_cx_2026"],
        "solution": "Resolution-focused knowledge design, step validation, and failure-loop analytics.",
    },
    {
        "slug": "ai_handoff_gap",
        "macro_theme": "support",
        "title": "Users in {vertical_label} get trapped between AI help and human help",
        "phrase": "The bot understood part of the issue, but it could not finish the job or hand me off cleanly.",
        "why_now": "AI adoption is accelerating faster than handoff design, producing frustrating half-resolved support journeys.",
        "severity": 80,
        "urgency": 79,
        "frequency": 83,
        "opportunity": 87,
        "ai_fit": 92,
        "sources": ["gartner_service_2026", "medallia_cx_2026", "qualtrics_cx_2026"],
        "solution": "Conversation memory, escalation contracts, and bot-to-human state transfer.",
    },
    {
        "slug": "feedback_void",
        "macro_theme": "support",
        "title": "Users report problems in {vertical_label} but feel nothing changes",
        "phrase": "I gave feedback, but it seemed to disappear into a black hole.",
        "why_now": "Brands collect more data, yet many departments still fail to act on critical insight.",
        "severity": 69,
        "urgency": 64,
        "frequency": 78,
        "opportunity": 76,
        "ai_fit": 70,
        "sources": ["medallia_cx_2026", "qualtrics_cx_2026"],
        "solution": "Closed-loop feedback orchestration and action-trace dashboards.",
    },
    {
        "slug": "privacy_transparency_gap",
        "macro_theme": "privacy",
        "title": "Users do not understand how {vertical_label} uses personal data",
        "phrase": "I might share data if I trusted how it would be used, but right now I do not.",
        "why_now": "Consumers show willingness to share data when transparency is clear, but most products still explain this poorly.",
        "severity": 74,
        "urgency": 69,
        "frequency": 80,
        "opportunity": 82,
        "ai_fit": 71,
        "sources": ["qualtrics_cx_2026", "mcafee_scamiverse_2026"],
        "solution": "Plain-language data notices, purpose-level controls, and permission history.",
    },
    {
        "slug": "onboarding_dropoff",
        "macro_theme": "conversion",
        "title": "Users abandon {vertical_label} onboarding before seeing value",
        "phrase": "I tried to sign up, but too many steps or checks made me leave.",
        "why_now": "Fraud controls, identity checks, and fragmented forms create growing onboarding friction across sectors.",
        "severity": 72,
        "urgency": 70,
        "frequency": 88,
        "opportunity": 88,
        "ai_fit": 78,
        "sources": ["transunion_fraud_2026", "qualtrics_cx_2026"],
        "solution": "Risk-adaptive onboarding, progressive profiling, and abandonment analytics.",
    },
    {
        "slug": "checkout_abandonment",
        "macro_theme": "conversion",
        "title": "Users in {vertical_label} abandon checkout when trust or cost changes too late",
        "phrase": "I was ready to buy, but hidden friction or uncertainty made me back out.",
        "why_now": "Late-stage pricing surprises, seller uncertainty, and payment trust issues keep eroding conversion.",
        "severity": 78,
        "urgency": 75,
        "frequency": 86,
        "opportunity": 91,
        "ai_fit": 76,
        "sources": ["qualtrics_cx_2026", "transunion_fraud_2026", "ftc_social_scams_2026"],
        "solution": "Transparent checkout, pre-verified totals, and trust-state messaging.",
    },
    {
        "slug": "hidden_fees",
        "macro_theme": "payments",
        "title": "Users discover hidden or confusing fees in {vertical_label} too late",
        "phrase": "The final price felt very different from what I thought I was agreeing to.",
        "why_now": "Fee sensitivity is high, and unclear pricing destroys trust even when the transaction technically succeeds.",
        "severity": 76,
        "urgency": 72,
        "frequency": 79,
        "opportunity": 81,
        "ai_fit": 70,
        "sources": ["qualtrics_cx_2026", "medallia_cx_2026"],
        "solution": "Price breakdowns, fee explainers, and cost-delta warnings.",
    },
    {
        "slug": "official_channel_confusion",
        "macro_theme": "trust",
        "title": "Users cannot tell which {vertical_label} channels are official and safe",
        "phrase": "I do not know whether to trust the message, app, account, or website that contacted me.",
        "why_now": "Scams increasingly mimic normal delivery, banking, government, and support communication patterns.",
        "severity": 89,
        "urgency": 86,
        "frequency": 82,
        "opportunity": 80,
        "ai_fit": 62,
        "sources": ["mcafee_scamiverse_2026", "ftc_social_scams_2026", "fbi_ic3_2026"],
        "solution": "Official-channel registries, signed notifications, and trust-verification UX.",
    },
    {
        "slug": "knowledge_fragmentation",
        "macro_theme": "support",
        "title": "Users in {vertical_label} get contradictory answers across help content, AI, and agents",
        "phrase": "The article said one thing, the bot said another, and the human told me something else again.",
        "why_now": "As teams add AI quickly, knowledge quality and consistency become harder to maintain.",
        "severity": 73,
        "urgency": 70,
        "frequency": 77,
        "opportunity": 79,
        "ai_fit": 84,
        "sources": ["gartner_service_2026", "medallia_cx_2026"],
        "solution": "Unified knowledge graph, answer verification, and source-aware support systems.",
    },
    {
        "slug": "identity_proofing_friction",
        "macro_theme": "identity",
        "title": "Legitimate users in {vertical_label} fail identity proofing while fraudsters still slip through",
        "phrase": "I was a real customer, but the verification flow treated me like a threat.",
        "why_now": "Fraud pressure is rising, but blunt controls increase abandonment and resentment for legitimate users.",
        "severity": 85,
        "urgency": 81,
        "frequency": 71,
        "opportunity": 86,
        "ai_fit": 73,
        "sources": ["transunion_fraud_2026", "gartner_service_2026"],
        "solution": "Adaptive proofing, low-friction trust signals, and fallback recovery lanes.",
    },
]
